# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='ti',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
