# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0003_auto_20180922_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='Bank',
        ),
    ]
