# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0004_auto_20180922_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='t',
            new_name='Account',
        ),
    ]
