# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0007_remove_snippet_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='original_code',
            new_name='Comment',
        ),
    ]
