# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0008_auto_20180922_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted_code',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Product_name',
            field=models.IntegerField(default=0),
        ),
    ]
