# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0009_auto_20180922_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='expiration',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
