# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0012_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='default_exposure',
            field=models.CharField(choices=[('Public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='Public', max_length=10),
        ),
        migrations.AlterField(
            model_name='pos',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='exposure',
            field=models.CharField(max_length=10),
        ),
    ]
