# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0013_auto_20181001_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='hits',
        ),
    ]
