# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0014_remove_snippet_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
