# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0016_auto_20181004_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='Comment',
            field=models.TextField(),
        ),
    ]
