# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0017_auto_20181005_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='Bank',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
