# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0018_auto_20181005_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Product_name',
            field=models.CharField(max_length=200),
        ),
    ]
