# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0019_auto_20181005_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='hits',
            field=models.IntegerField(default=0, help_text='Read only field. Will be updated after every visit to snippet.'),
        ),
    ]
